"""
Schede informative (pulsante "i") per ogni analizzatore: cosa fa, quando funziona, limiti, esempi,
spiegazione di ogni passo con un esempio concreto, riferimenti scientifici. Testi in italiano.
"""

GLOSSARIO = [
    ("CNN (Convolutional Neural Network)", "Rete neurale convoluzionale: una rete che 'scorre' piccoli filtri (es. 3×3 pixel) sull'immagine per riconoscere prima bordi e texture, poi forme sempre più complesse. È l'architettura standard per le immagini; le quattro reti del docente sono CNN."),
    ("Pesi / addestramento", "I pesi sono i milioni di numeri interni di una rete. Si 'imparano' mostrando alla rete migliaia di esempi etichettati (addestramento). Una rete 'non addestrata' ha pesi casuali e risponde a caso."),
    ("Pre-addestrato", "Modello i cui pesi sono già stati addestrati da altri (es. MiniVision, OpenAI) e distribuiti pubblicamente: dà risultati sensati da subito."),
    ("Zero-shot", "Usare un modello per un compito su cui non è mai stato addestrato, descrivendo il compito a parole (es. 'foto stampata di un volto'). Nessun esempio del nostro problema gli è mai stato mostrato."),
    ("Euristico", "Regola pratica basata su misure fisiche e soglie scelte a mano (es. 'se l'immagine è molto sfocata è probabilmente una ricattura'). Non impara dai dati: è spiegabile ma approssimato, e le soglie vanno calibrate."),
    ("Presentation attack (PA)", "Attacco di presentazione: mostrare alla telecamera un oggetto fisico falso (foto stampata, video su schermo, maschera) per farsi passare per qualcun altro. Lo definisce lo standard ISO/IEC 30107-1."),
    ("Bona fide", "Presentazione genuina: una persona reale davanti alla camera."),
    ("Liveness detection / PAD", "Rilevamento della 'vivezza' (Presentation Attack Detection): capire se davanti alla camera c'è una persona viva o un artefatto."),
    ("APCER", "Attack Presentation Classification Error Rate: quota di attacchi che il sistema accetta erroneamente come reali (ISO/IEC 30107-3). Più è basso, più il sistema è sicuro."),
    ("BPCER", "Bona fide Presentation Classification Error Rate: quota di persone reali rifiutate come attacco. Più è basso, più il sistema è comodo da usare."),
    ("ACER", "Media di APCER e BPCER: un solo numero per confrontare sistemi."),
    ("EER", "Equal Error Rate: il punto in cui APCER e BPCER coincidono, spostando la soglia di decisione."),
    ("Cross-dataset", "Addestrare su un dataset e testare su un altro (camera, luce, attacchi diversi). Misura la capacità di generalizzare: è il punto debole di quasi tutti i metodi e il tema della tesi."),
    ("Softmax", "Funzione che trasforma i numeri in uscita da una rete in probabilità che sommano a 1."),
    ("Grad-CAM", "Tecnica che colora le zone dell'immagine che hanno pesato di più nella decisione della rete: serve a 'vedere dove guarda'."),
    ("LBP", "Local Binary Pattern: codice a 8 bit che descrive la micro-texture attorno a ogni pixel confrontandolo con i vicini."),
    ("FFT / spettro", "Trasformata di Fourier: scompone l'immagine in frequenze. Basse = forme grandi, alte = dettagli fini e grana."),
]

_KUZNETSOV_PASSI = {
    "input": {"spiegazione": "L'immagine viene letta come matrice di numeri (altezza × larghezza × 3 canali colore). Ogni passo successivo è una trasformazione di questa matrice.", "esempio": "Una foto 640×480 diventa 921.600 numeri tra 0 e 255."},
    "face": {"spiegazione": "RetinaFace individua il volto e restituisce il riquadro. Lavorare solo sul volto elimina lo sfondo, che non contiene indizi di vivezza.", "esempio": "Se nella foto c'è anche una libreria dietro, la rete non deve 'imparare' che le librerie sono reali."},
    "crop": {"spiegazione": "Ritaglio del riquadro con un margine del 15%, reso quadrato: include contorno del viso e capelli, dove spesso si vede il bordo di una foto stampata.", "esempio": "In un attacco con foto stampata, il margine cattura il bordo bianco del foglio."},
    "resize": {"spiegazione": "Le reti del docente accettano solo 256×256 pixel: ogni immagine viene portata a quella dimensione.", "esempio": "Un ritaglio 300×300 viene ridotto; uno 120×120 viene ingrandito (perdendo dettaglio: per questo il controllo qualità)."},
    "bilateral": {"spiegazione": "Filtro che attenua il rumore del sensore ma conserva i bordi netti (a differenza di una sfocatura normale).", "esempio": "La grana ISO di una foto scattata al buio viene ridotta senza sfocare il contorno degli occhi."},
    "clahe": {"spiegazione": "Equalizzazione adattiva del contrasto sul solo canale di luminosità: rende visibili i dettagli fini della pelle anche in foto piatte.", "esempio": "Pori e piccole rughe diventano più evidenti; in una foto stampata emerge invece il retino di stampa."},
    "usm": {"spiegazione": "Unsharp masking: esalta i dettagli ad alta frequenza sottraendo una versione sfocata.", "esempio": "Se l'immagine è una ricattura da schermo, la mancanza di dettagli fini diventa più evidente alla rete."},
    "gamma": {"spiegazione": "Correzione gamma e piccola scala lineare: uniformano la luminosità tra foto scattate con luci diverse.", "esempio": "Una foto sottoesposta e una sovraesposta della stessa persona arrivano alla rete con luminosità simile."},
    "quality": {"spiegazione": "Misure analoghe a quelle con cui il docente scarta le immagini di bassa qualità dal dataset: nitidezza, contrasto, luminosità (senza il suo punteggio composito).", "esempio": "Un'immagine con nitidezza molto bassa verrebbe esclusa dal training; qui segnala che il verdetto può essere incerto."},
    "normalize": {"spiegazione": "I valori 0–255 diventano 0–1: le reti neurali imparano meglio con numeri piccoli e centrati.", "esempio": "Il pixel 128 diventa 0,502."},
    "cnn": {"spiegazione": "Passaggio in avanti nella rete: i filtri convoluzionali estraggono texture e forme, i layer densi combinano tutto in due numeri (reale / attacco).", "esempio": "Con pesi addestrati, il filtro n.7 potrebbe 'accendersi' sul pattern periodico dei pixel di uno schermo."},
    "features": {"spiegazione": "Visualizzazione delle 16 mappe di attivazione del primo layer: mostrano cosa la rete percepisce all'inizio.", "esempio": "Alcune mappe evidenziano bordi verticali, altre orizzontali, altre le zone luminose."},
    "gradcam": {"spiegazione": "Grad-CAM colora le regioni che hanno pesato di più nella decisione.", "esempio": "Se la mappa è calda sullo sfondo e non sul volto, la rete sta usando un indizio sbagliato: un problema tipico nel cross-dataset."},
    "softmax": {"spiegazione": "Le due uscite diventano probabilità che sommano a 1; si decide con soglia 0,5.", "esempio": "Uscita [2,1, −0,3] → P(reale) 0,92, P(attacco) 0,08 → reale."},
    "verdict": {"spiegazione": "Decisione finale con confidenza. Le metriche ISO (APCER, BPCER) si misurano su interi dataset, non su una singola foto.", "esempio": "Su 1.000 attacchi, se 20 vengono accettati l'APCER è 2%."},
}

_KUZ_RIF = [
    {"testo": "Kuznetsov, Frontoni, Romeo, Rosati, Maranesi, Muscatello. Deep Learning Models for Robust Facial Liveness Detection. Multimedia Tools and Applications 85(3), 2026. DOI 10.1007/s11042-026-21445-w", "url": "https://arxiv.org/abs/2508.09094"},
    {"testo": "Kuznetsov, Zakharov, Frontoni, Maranesi. AttackNet: Enhancing Biometric Security via Tailored Convolutional Neural Network Architectures for Liveness Detection. Computers & Security 141, 2024", "url": "https://arxiv.org/abs/2402.03769"},
    {"testo": "Nurpeisova, Shaushenova, Kuznetsov et al. Deep Residual Learning for Face Anti-Spoofing: A Mathematical Framework for Optimized Skip Connections. Technologies 13(9), 2025", "url": "https://www.mdpi.com/2227-7080/13/9/413"},
    {"testo": "Kuznetsov et al. Cross-Database Liveness Detection: Insights from Comparative Biometric Analysis. CEUR-WS 3608, 2023", "url": "https://arxiv.org/abs/2401.16232"},
    {"testo": "Selvaraju et al. Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization. ICCV 2017", "url": "https://arxiv.org/abs/1610.02391"},
    {"testo": "Repository ufficiale del docente (MIT)", "url": "https://github.com/KuznetsovKarazin/liveness-detection"},
]


def _kuz(nome, extra_cosa, forza_extra):
    return {
        "cosa_fa": f"{nome} è una rete neurale convoluzionale (CNN) progettata dal prof. Kuznetsov per distinguere volti reali da attacchi di presentazione. Riceve il volto a 256×256 pixel dopo il preprocessing del suo dataset e produce due probabilità: bona fide / attacco. {extra_cosa}",
        "quando_funziona": ["Foto stampate e replay su schermo simili a quelli visti in addestramento (intra-dataset: 99,7–99,9% di accuracy nel paper).",
                            "Immagini nitide, volto frontale, illuminazione simile al training."] + forza_extra,
        "limiti": ["Ogni variante è addestrata su un solo dataset pubblico (NUAA, CASIA-FASD, CelebA-Spoof o il sintetico SynthASpoof) con lo script della tesi; le versioni 'split 80/20 del docente' non vanno valutate sul proprio dataset perché ne hanno visto anche il test.",
                   "Generalizza male a dataset diversi: nel paper del docente ~52% di accuracy media in cross-dataset con training su un solo dataset.",
                   "Non vede il tempo: nessun indizio da movimento o battito di ciglia."],
        "esempi": [{"titolo": "Foto stampata", "testo": "La rete impara la grana della stampa e la perdita di dettaglio: con pesi addestrati, la mappa Grad-CAM si accende sulle zone di pelle piatta."},
                   {"titolo": "Replay su smartphone", "testo": "Il pattern periodico dei pixel e i riflessi dello schermo attivano i filtri del primo blocco convoluzionale."},
                   {"titolo": "Maschera 3D (3DMAD)", "testo": "La maschera ha rilievo ma texture rigida e senza pori: i filtri ad alta frequenza rispondono in modo diverso dalla pelle."}],
        "passi": _KUZNETSOV_PASSI,
        "riferimenti": _KUZ_RIF,
    }


DOCS = {
    "livenessnet": _kuz("LivenessNet", "È la baseline: 2 blocchi convoluzionali (16 e 32 filtri), BatchNorm, dropout, un layer denso da 64. 8,4 milioni di parametri.", ["Veloce e leggera: utile come riferimento per misurare il guadagno delle AttackNet."]),
    "attacknet_v1": _kuz("AttackNet V1", "Aggiunge connessioni residue per concatenazione (l'ingresso del blocco viene affiancato alla sua uscita), attivazioni LeakyReLU e tanh nel layer denso. 33,6 milioni di parametri.", ["Nel paper Technologies 2025 è la migliore su MSSpoof: 99,6% accuracy, HTER 0,004 (baseline 94,35%)."]),
    "attacknet_v2_1": _kuz("AttackNet V2.1", "Stessa struttura di V1 con dropout pieno anche nei blocchi convoluzionali e attivazione tanh separata dal layer denso. 33,6 milioni di parametri.", ["Regolarizzazione più forte: meno overfitting su dataset piccoli."]),
    "attacknet_v2_2": _kuz("AttackNet V2.2", "Le connessioni residue sommano invece di concatenare (come in ResNet): metà dei parametri (16,8 milioni), training due volte più veloce.", ["Nel paper del docente è il modello con la migliore generalizzazione cross-dataset e il miglior compromesso accuratezza/efficienza (16 MB di memoria)."]),
    "minifasnet": {
        "cosa_fa": "MiniFASNet è una famiglia di reti leggere (derivate da MobileNet) pubblicata da MiniVision per la liveness 'silenziosa', cioè senza chiedere all'utente di muoversi. Due reti guardano il volto a due scale diverse (2,7× e 4×) e le loro probabilità vengono sommate. È un modello pre-addestrato: dà un verdetto sensato senza alcun addestramento nostro, ma su dati che non conosciamo.",
        "quando_funziona": ["Foto stampate, replay su telefono/monitor e maschere di carta ripresi con camera frontale (scenario smartphone).", "Quando nel ritaglio a 4× si vedono la cornice della foto, il bordo dello schermo o le mani che lo reggono."],
        "limiti": ["Addestrato su ~360.000 immagini proprietarie: non sappiamo esattamente quali attacchi ha visto.", "Input 80×80: dettagli finissimi (pori, retino) vanno persi; si affida al contesto.", "Non confrontabile 1:1 con le reti del docente (dati e protocollo diversi)."],
        "esempi": [{"titolo": "Immagine di prova 'reale' (T1)", "testo": "Entrambe le reti danno P(reale) > 0,98: fusione 99%."}, {"titolo": "Immagine di prova 'attacco' (F1, foto stampata)", "testo": "La rete a 4× vede il bordo del foglio e spinge verso 'attacco': fusione 70–73% attacco."}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine come matrice BGR.", "esempio": "Come per tutti gli algoritmi."},
            "face": {"spiegazione": "RetinaFace fornisce il riquadro del volto: il centro di quel riquadro guida entrambi i ritagli.", "esempio": "Riquadro 200×260 px centrato sul naso."},
            "crop27": {"spiegazione": "Il riquadro viene allargato di 2,7 volte attorno al centro e ridotto a 80×80: vede il volto intero con un po' di contesto.", "esempio": "Da un riquadro 200×260 si ottiene una patch di 540×700 px, poi 80×80."},
            "crop40": {"spiegazione": "Allargamento di 4 volte: entra molto contesto (spalle, mani, cornice).", "esempio": "Se la persona regge un telefono, il telefono compare nella patch."},
            "net27": {"spiegazione": "MiniFASNetV2: convoluzioni depthwise-separable, uscita a 3 classi (0 e 2 = attacco, 1 = reale).", "esempio": "Uscita [0,05, 0,93, 0,02] → reale."},
            "net40": {"spiegazione": "MiniFASNetV1SE: come sopra con blocchi Squeeze-and-Excitation (attenzione sui canali).", "esempio": "Se vede la cornice bianca del foglio: [0,80, 0,15, 0,05]."},
            "fuse": {"spiegazione": "Somma delle probabilità delle due reti divisa per 2: le due scale si correggono a vicenda.", "esempio": "[0,05,0,93,0,02] + [0,80,0,15,0,05] → [0,43,0,54,0,03] → reale ma con poca confidenza."},
            "verdict": {"spiegazione": "Reale se P(reale) fusa ≥ 0,5, altrimenti attacco.", "esempio": "Indice 1 → 'volto reale'."},
        },
        "riferimenti": [{"testo": "MiniVision AI. Silent-Face-Anti-Spoofing (codice e pesi, Apache-2.0), 2020", "url": "https://github.com/minivision-ai/Silent-Face-Anti-Spoofing"},
                        {"testo": "Howard et al. MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications, 2017", "url": "https://arxiv.org/abs/1704.04861"},
                        {"testo": "Hu, Shen, Sun. Squeeze-and-Excitation Networks. CVPR 2018", "url": "https://arxiv.org/abs/1709.01507"},
                        {"testo": "Deng et al. RetinaFace: Single-stage Dense Face Localisation in the Wild. CVPR 2020 (rilevatore volto usato)", "url": "https://arxiv.org/abs/1905.00641"}],
    },
    "clip_zeroshot": {
        "cosa_fa": "CLIP (OpenAI) è un modello che ha imparato ad associare 400 milioni di immagini alle loro didascalie. Proietta immagine e testo nello stesso spazio: possiamo quindi chiedergli 'questa immagine somiglia più a «un volto reale» o a «una foto stampata di un volto»?' senza alcun addestramento. FLIP (ICCV 2023) ha mostrato che questa impostazione, con un leggero fine-tuning, batte le CNN nel cross-dataset.",
        "quando_funziona": ["Attacchi 'visibili' nel contesto: bordi di carta, schermi, mani, riflessi, maschere evidenti.", "Generalizza a scene mai viste perché non dipende da un dataset di anti-spoofing."],
        "limiti": ["Zero-shot: un replay di alta qualità a tutto schermo può sembrare 'una persona' anche a CLIP.", "Sensibile alla scelta delle frasi (prompt engineering).", "Modello grande (150 M parametri): più lento delle reti leggere."],
        "esempi": [{"titolo": "Foto stampata con bordo visibile", "testo": "La frase 'a printed photo of a face' ottiene la similarità più alta: attacco."}, {"titolo": "Selfie reale", "testo": "'a real person taking a selfie' vince: reale con margine ampio."}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"},
            "face": {"spiegazione": "Riquadro del volto da RetinaFace.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio con margine ampio (35%): il contesto è proprio ciò che i prompt di attacco descrivono.", "esempio": "Le mani che reggono un telefono restano nel ritaglio."},
            "prep": {"spiegazione": "Ridimensionamento a 224×224 e normalizzazione; l'immagine è vista come 49 tessere (patch) da 32×32.", "esempio": "Una tessera copre circa un occhio."},
            "img_enc": {"spiegazione": "Un Vision Transformer trasforma le tessere in un vettore di 512 numeri che riassume il contenuto visivo.", "esempio": "Immagini simili (due selfie) hanno vettori vicini."},
            "prompts": {"spiegazione": "Le ipotesi vengono scritte in inglese, lingua dei dati di CLIP: 4 frasi 'reale' e 6 'attacco'.", "esempio": "'a face displayed on a phone screen'."},
            "txt_enc": {"spiegazione": "Un Transformer testuale porta ogni frase nello stesso spazio a 512 dimensioni.", "esempio": "Le frasi 'printed photo' e 'photograph of a photograph' finiscono vicine tra loro."},
            "sim": {"spiegazione": "Similarità coseno immagine-frase × 100: più alta = descrizione più adatta.", "esempio": "Reale: 27,1 · foto stampata: 22,4."},
            "softmax": {"spiegazione": "Le similarità di ogni classe vengono riassunte con una media in scala logaritmica (così 4 frasi 'reale' e 6 'attacco' pesano uguale), poi una softmax a due vie dà P(reale).", "esempio": "P(reale) 0,71 → reale."},
            "verdict": {"spiegazione": "Decisione zero-shot con la frase più vicina come spiegazione.", "esempio": "'Attacco 64% · frase più vicina: un volto su un monitor'."},
        },
        "riferimenti": [{"testo": "Radford et al. Learning Transferable Visual Models From Natural Language Supervision (CLIP). ICML 2021", "url": "https://arxiv.org/abs/2103.00020"},
                        {"testo": "Srivatsan, Naseer, Nandakumar. FLIP: Cross-domain Face Anti-spoofing with Language Guidance. ICCV 2023", "url": "https://arxiv.org/abs/2309.16649"},
                        {"testo": "Dosovitskiy et al. An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale (ViT). ICLR 2021", "url": "https://arxiv.org/abs/2010.11929"}],
    },
    "depth": {
        "cosa_fa": "Depth Anything V2 ricostruisce da una singola foto una mappa di profondità (quanto è vicino ogni pixel). Un volto reale è una superficie con rilievo (naso avanti, orecchie indietro); una foto o uno schermo sono piatti. L'idea di usare la profondità come indizio di liveness è di Liu, Jourabloo e Liu (CVPR 2018), che la usavano come supervisione ausiliaria delle CNN.",
        "quando_funziona": ["Ritagli che includono il supporto dell'attacco (foglio, telefono, monitor): la geometria del piano diventa evidente.", "Maschere di carta piatte, foto piegate, schermi inclinati."],
        "limiti": ["Il modello 'sa' che un volto ha rilievo e tende a ricostruirlo anche da una foto ben stampata: su ritagli stretti l'indizio è debole.", "Profondità relativa, non metrica: le soglie sono indicative."],
        "esempi": [{"titolo": "Persona reale", "testo": "Naso più vicino, bordi del viso più lontani: residuo del piano alto, rilievo positivo."}, {"titolo": "Foto stampata piatta con cornice visibile", "testo": "Profondità quasi costante su tutta l'area: residuo basso → attacco."}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio con margine del 60%: serve vedere il contorno per capire se il volto 'esce' dal piano.", "esempio": "Spalle e sfondo entrano nel ritaglio."},
            "prep": {"spiegazione": "Ridimensionamento a 518 px (multiplo di 14, dimensione delle patch del ViT) e normalizzazione ImageNet.", "esempio": "—"},
            "dpt": {"spiegazione": "ViT-Small (DINOv2) + testa DPT: predice per ogni pixel una profondità relativa. Addestrato su 62 milioni di immagini.", "esempio": "Valori alti sul naso, bassi sullo sfondo."},
            "depthmap": {"spiegazione": "Normalizzazione 0–1 dentro il riquadro del volto per confrontare immagini diverse.", "esempio": "Naso ≈ 1, orecchie ≈ 0,3."},
            "plane": {"spiegazione": "Si adatta un piano ai valori di profondità: se il volto è piatto, il piano lo descrive quasi perfettamente (residuo piccolo).", "esempio": "Foto stampata: residuo 0,03; volto reale: 0,12."},
            "relief": {"spiegazione": "Differenza di profondità tra il centro (naso) e i bordi (guance/orecchie).", "esempio": "Volto reale: +0,35; foto: +0,05."},
            "score": {"spiegazione": "Media delle due componenti con soglie indicative.", "esempio": "Residuo alto e rilievo alto → P(reale) 0,8."},
            "verdict": {"spiegazione": "Esito orientativo.", "esempio": "—"},
        },
        "riferimenti": [{"testo": "Yang et al. Depth Anything V2. NeurIPS 2024", "url": "https://arxiv.org/abs/2406.09414"},
                        {"testo": "Liu, Jourabloo, Liu. Learning Deep Models for Face Anti-Spoofing: Binary or Auxiliary Supervision. CVPR 2018", "url": "https://openaccess.thecvf.com/content_cvpr_2018/html/Liu_Learning_Deep_Models_CVPR_2018_paper.html"},
                        {"testo": "Oquab et al. DINOv2: Learning Robust Visual Features without Supervision. TMLR 2024", "url": "https://arxiv.org/abs/2304.07193"},
                        {"testo": "Ranftl, Bochkovskiy, Koltun. Vision Transformers for Dense Prediction (DPT). ICCV 2021", "url": "https://arxiv.org/abs/2103.13413"}],
    },
    "facemesh": {
        "cosa_fa": "MediaPipe Face Landmarker stima 478 punti 3D del volto (contorni, occhi, iride, bocca), la posa della testa e 52 'blendshape' che descrivono l'espressione. Su una foto singola descrive la geometria; su un video permette di misurare battito di ciglia e movimenti, che una foto stampata non può produrre.",
        "quando_funziona": ["Analisi video: battito di ciglia, rotazioni della testa coerenti in 3D (liveness attiva o passiva temporale).", "Controllo di plausibilità: posa estrema o mesh deformata segnalano immagini anomale."],
        "limiti": ["La coordinata z è predetta da un modello canonico del viso: anche una foto stampata ottiene un rilievo 'da volto'.", "Su una singola immagine il punteggio è debole per costruzione: non pesa nel consenso."],
        "esempi": [{"titolo": "Video di persona reale", "testo": "eyeBlinkLeft/Right salgono sopra 0,5 ogni 3–5 secondi: battito di ciglia."}, {"titolo": "Video con foto stampata", "testo": "Blendshape costanti, nessun battito, posa che cambia solo con il movimento rigido del foglio."}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio quadrato con margine 35% (il modello vuole il volto intero).", "esempio": "—"},
            "mesh": {"spiegazione": "BlazeFace trova il volto; Attention Mesh regredisce 468 punti + 10 dell'iride con z relativa e la matrice di posa.", "esempio": "Il punto 1 è la punta del naso, 33 e 263 gli angoli esterni degli occhi."},
            "landmarks": {"spiegazione": "Disegno della maglia triangolare; colore = profondità stimata.", "esempio": "Naso chiaro (vicino), tempie scure (lontane)."},
            "pose": {"spiegazione": "Dalla matrice 4×4 si estraggono yaw, pitch e roll.", "esempio": "yaw −20° = testa girata verso destra dell'osservatore."},
            "zrelief": {"spiegazione": "Dispersione della z e differenza naso-guance, normalizzate sulla larghezza del volto.", "esempio": "Rilievo 0,08 su volto frontale."},
            "blend": {"spiegazione": "52 coefficienti 0–1 (occhi chiusi, sorriso, bocca aperta...).", "esempio": "eyeBlinkLeft 0,9 = occhio sinistro chiuso."},
            "score": {"spiegazione": "Riassunto di posa, rilievo e stato degli occhi. Nessun punteggio: sui campioni di prova anche le foto stampate ottengono un rilievo da volto reale.", "esempio": "Foto stampata F2: rilievo 0,68, come un volto vero → indizio inutile da solo."},
            "verdict": {"spiegazione": "Nessun verdetto su singola immagine; nel video diventa un rilevatore (battito di ciglia, movimento 3D coerente).", "esempio": "Video reale: eyeBlink supera 0,5 ogni pochi secondi."},
        },
        "riferimenti": [{"testo": "Kartynnik, Ablavatski, Grishchenko, Grundmann. Real-time Facial Surface Geometry from Monocular Video on Mobile GPUs. CVPRW 2019", "url": "https://arxiv.org/abs/1907.06724"},
                        {"testo": "Grishchenko et al. Attention Mesh: High-fidelity Face Mesh Prediction in Real-time. CVPRW 2020", "url": "https://arxiv.org/abs/2006.10962"},
                        {"testo": "Bazarevsky et al. BlazeFace: Sub-millisecond Neural Face Detection on Mobile GPUs. 2019", "url": "https://arxiv.org/abs/1907.05047"},
                        {"testo": "Pan, Sun, Wu, Lao. Eyeblink-based Anti-Spoofing in Face Recognition from a Generic Webcamera. ICCV 2007 (battito di ciglia come liveness)", "url": "https://doi.org/10.1109/ICCV.2007.4409068"}],
    },
    "lbp": {
        "cosa_fa": "Local Binary Pattern descrive la micro-texture: per ogni pixel confronta i vicini e produce un codice binario. Määttä, Hadid e Pietikäinen (2011) hanno mostrato che gli istogrammi LBP separano bene pelle reale da foto stampate e schermi; Boulkenafet et al. (2016) hanno esteso l'idea agli spazi colore HSV e YCbCr. Il vettore di feature viene classificato da una SVM.",
        "quando_funziona": ["Foto stampate (grana e retino di stampa) e replay su schermo (griglia di pixel), con immagini nitide.", "Metodo leggerissimo, interpretabile, storicamente lo stato dell'arte pre-deep learning."],
        "limiti": ["Serve una SVM addestrata sulle firme LBP dei dataset: senza, il metodo estrae la firma ma non dà verdetto.", "Sensibile a sfocatura, compressione JPEG e risoluzione: cambiando camera cala molto (problema cross-dataset)."],
        "esempi": [{"titolo": "Pelle reale", "testo": "Istogramma LBP con molti pattern 'uniformi' e distribuiti; saturazione HSV naturale."}, {"titolo": "Replay su LCD", "testo": "Pattern periodici e canale S 'spento': l'istogramma cambia forma."}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio quadrato senza margine.", "esempio": "—"},
            "resize": {"spiegazione": "64×64 come nel metodo originale: rende la scala della texture confrontabile.", "esempio": "—"},
            "gray": {"spiegazione": "Conversione in luminanza: la micro-texture è un fenomeno di intensità.", "esempio": "Y = 0,299R + 0,587G + 0,114B."},
            "lbp81": {"spiegazione": "8 vicini a raggio 1, immagine divisa in 3×3 regioni: istogrammi concatenati (10 bin uniformi × 9 celle = 90 valori; la variante 'uniform' di scikit-image ha P+2 bin, meno dei 59 del LBP u2 originale).", "esempio": "Codice 00111100 → pattern uniforme (2 transizioni)."},
            "lbp82": {"spiegazione": "Raggio 2: texture a scala media.", "esempio": "—"},
            "lbp162": {"spiegazione": "16 vicini a raggio 2: pattern più ampi.", "esempio": "—"},
            "color": {"spiegazione": "LBP su H, S, V, Y, Cr, Cb: gli attacchi alterano soprattutto S e la crominanza.", "esempio": "Foto stampata: canale S piatto."},
            "hist": {"spiegazione": "Tutti gli istogrammi concatenati = firma di texture.", "esempio": "Vettore da qualche centinaio di numeri."},
            "svm": {"spiegazione": "SVM con kernel RBF separa le firme.", "esempio": "—"},
            "verdict": {"spiegazione": "Decisione.", "esempio": "—"},
        },
        "riferimenti": [{"testo": "Määttä, Hadid, Pietikäinen. Face spoofing detection from single images using micro-texture analysis. IJCB 2011", "url": "https://ieeexplore.ieee.org/document/6117510"},
                        {"testo": "Boulkenafet, Komulainen, Hadid. Face Spoofing Detection Using Colour Texture Analysis. IEEE TIFS 11(8), 2016", "url": "https://ieeexplore.ieee.org/document/7454730"},
                        {"testo": "Ojala, Pietikäinen, Mäenpää. Multiresolution gray-scale and rotation invariant texture classification with LBP. IEEE TPAMI 2002", "url": "https://ieeexplore.ieee.org/document/1017623"}],
    },
    "fourier": {
        "cosa_fa": "Analizza l'immagine nel dominio delle frequenze. Li et al. (2004) hanno osservato che una foto stampata e ri-fotografata perde le alte frequenze (dettagli fini): il loro High Frequency Descriptor misura questa perdita. Garcia e de Queiroz (2015) rilevano invece i pattern moiré, picchi periodici prodotti dall'interferenza tra i pixel di uno schermo e quelli del sensore.",
        "quando_funziona": ["Ricatture sfocate o a bassa risoluzione, stampe di qualità media.", "Replay su schermo ripreso da vicino (moiré evidente)."],
        "limiti": ["Euristico: soglie fissate su poche immagini, da calibrare sui dataset.", "Una foto reale sfocata o compressa può sembrare 'attacco'; una stampa ad altissima qualità può passare."],
        "esempi": [{"titolo": "Immagini di prova", "testo": "HFD 0,38 per il volto reale contro 0,27–0,29 per le due foto stampate."}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio quadrato con margine 10%.", "esempio": "—"},
            "gray": {"spiegazione": "256×256 in scala di grigi.", "esempio": "—"},
            "window": {"spiegazione": "Finestra di Hann: evita frequenze spurie dovute ai bordi del ritaglio.", "esempio": "—"},
            "fft": {"spiegazione": "FFT 2D, spettro centrato, scala logaritmica.", "esempio": "Centro luminoso = basse frequenze."},
            "radial": {"spiegazione": "Energia sommata per anelli concentrici: curva energia(frequenza).", "esempio": "Una ricattura ha coda alta-frequenza più bassa."},
            "hfd": {"spiegazione": "Quota di energia oltre 1/3 della frequenza massima.", "esempio": "0,38 reale vs 0,28 stampa (campioni)."},
            "moire": {"spiegazione": "Picchi isolati sopra la media locale nella banda media.", "esempio": "Replay LCD: picchi simmetrici a ±(fx, fy)."},
            "score": {"spiegazione": "0,6·HFD + 0,4·moiré con soglie indicative.", "esempio": "—"},
            "verdict": {"spiegazione": "Esito orientativo.", "esempio": "—"},
        },
        "riferimenti": [{"testo": "Li, Wang, Tan, Jain. Live face detection based on the analysis of Fourier spectra. SPIE 5404, 2004", "url": "https://doi.org/10.1117/12.541955"},
                        {"testo": "Garcia, de Queiroz. Face-Spoofing 2D-Detection Based on Moiré-Pattern Analysis. IEEE TIFS 10(4), 2015", "url": "https://ieeexplore.ieee.org/document/7031941"}],
    },
    "ida": {
        "cosa_fa": "Image Distortion Analysis (Wen, Han, Jain 2015): un attacco è una ri-cattura, e ogni ri-cattura introduce distorsioni misurabili: riflessi speculari del supporto, sfocatura, gamma cromatica compressa, meno colori distinti. Le 16 misure (versione ridotta del vettore a 121 valori dell'articolo) formano un vettore che una SVM classifica; senza SVM usiamo un'euristica.",
        "quando_funziona": ["Replay su schermo (riflessi, colori impoveriti) e stampe lucide.", "Metodo veloce e interpretabile, buono in combinazione con LBP."],
        "limiti": ["Euristico finché la SVM non è addestrata.", "Dipende da illuminazione e camera: soglie da calibrare per dataset."],
        "esempi": [{"titolo": "Immagini di prova", "testo": "Foto stampata F2: 29% di pixel speculari contro 3% del volto reale."}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio 256×256 con margine 10%.", "esempio": "—"},
            "specular": {"spiegazione": "Pixel molto luminosi e poco saturi = riflessi: percentuale, media, varianza.", "esempio": "Carta lucida sotto una lampada: 20–30%."},
            "blur": {"spiegazione": "Varianza del Laplaciano e rapporto sfocato/nitido.", "esempio": "Ricattura: varianza < 100."},
            "chroma": {"spiegazione": "Media, deviazione e asimmetria di H, S, V.", "esempio": "Schermo: S media bassa."},
            "diversity": {"spiegazione": "Colori distinti dopo quantizzazione e quota dei 100 più frequenti.", "esempio": "Volto reale: > 1.500 colori distinti."},
            "vector": {"spiegazione": "Le 16 misure concatenate (l'articolo originale ne usa 121, con istogrammi completi di colore).", "esempio": "—"},
            "clf": {"spiegazione": "SVM se addestrata, altrimenti euristica pesata.", "esempio": "—"},
            "verdict": {"spiegazione": "Esito.", "esempio": "—"},
        },
        "riferimenti": [{"testo": "Wen, Han, Jain. Face Spoof Detection With Image Distortion Analysis. IEEE TIFS 10(4), 2015", "url": "https://doi.org/10.1109/TIFS.2015.2400395"},
                        {"testo": "Galbally, Marcel, Fierrez. Image Quality Assessment for Fake Biometric Detection. IEEE TIP 23(2), 2014", "url": "https://ieeexplore.ieee.org/document/6671991"}],
    },
    "dog": {
        "cosa_fa": "Difference of Gaussians (Tan, Li, Liu, Jiang 2010): è il metodo con cui è stato presentato il dataset NUAA. Il volto in scala di grigi a 64×64 viene filtrato con la differenza di due gaussiane (σ 0,5 e 1,0): restano solo le frequenze medie, dove una foto stampata e rifotografata si distingue da un volto dal vivo. Sull'immagine filtrata si calcolano un istogramma, il profilo dello spettro di Fourier (Peixoto et al. 2011), quattro statistiche e si tiene l'immagine stessa ridotta a 32×32; una regressione logistica addestrata sui dataset della tesi dà il verdetto, come nell'articolo.",
        "quando_funziona": ["Foto stampate riprese da webcam, come in NUAA: perdita di dettaglio e retino di stampa cambiano la banda media.", "Metodo leggerissimo (millisecondi) e interamente spiegabile: ogni valore ha un significato fisico."],
        "limiti": ["Senza classificatore addestrato non c'è verdetto.", "Sensibile a sfocatura e compressione: una foto reale sfocata assomiglia a una stampa.", "Non vede colore né riflessi: da leggere insieme a LBP e IDA."],
        "esempi": [{"titolo": "Volto dal vivo", "testo": "Risposta DoG con code lunghe (molta struttura fine) e più energia alle alte frequenze."}, {"titolo": "Stampa A4", "testo": "Valori concentrati vicino a zero: la stampa ha appiattito i dettagli."}],
        "riferimenti": [{"testo": "Tan, Li, Liu, Jiang, Face Liveness Detection from a Single Image with Sparse Low Rank Bilinear Discriminative Model, ECCV 2010", "url": "https://doi.org/10.1007/978-3-642-15567-3_37"}, {"testo": "Peixoto, Michelassi, Rocha, Face liveness detection under bad illumination conditions, ICIP 2011", "url": "https://doi.org/10.1109/ICIP.2011.6116484"}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio quadrato senza margine.", "esempio": "—"},
            "gray": {"spiegazione": "Luminanza a 64×64, come nell'articolo.", "esempio": "—"},
            "dog": {"spiegazione": "Differenza tra due sfocature gaussiane: passa-banda sulle frequenze medie.", "esempio": "σ = 0,5 e 1,0."},
            "hist": {"spiegazione": "Istogramma della risposta normalizzata (32 bin tra −4σ e +4σ).", "esempio": "—"},
            "fft": {"spiegazione": "Spettro dell'immagine filtrata: profilo radiale in 16 bande e quota alle alte frequenze.", "esempio": "—"},
            "features": {"spiegazione": "1.076 valori: istogramma, profilo, statistiche e l'immagine DoG ridotta a 32×32 (i pixel filtrati di Tan et al.).", "esempio": "—"},
            "clf": {"spiegazione": "Regressione logistica (L2) addestrata con scripts/train_classic.py sullo split ufficiale di training, come la regressione sparsa dell'articolo.", "esempio": "—"},
            "verdict": {"spiegazione": "P(reale) ≥ 0,5 → reale.", "esempio": "—"},
        },
    },
    "iqa": {
        "cosa_fa": "Image Quality Assessment (Galbally, Marcel, Fierrez 2014): un attacco è una ri-cattura e ogni ri-cattura degrada l'immagine. Si misurano 18 indici di qualità: 12 confrontano l'immagine con una sua copia appena sfocata (se cambia poco, era già degradata), 6 la valutano da sola (blocchi JPEG, alte/basse frequenze, nitidezza, rumore, entropia). Una SVM addestrata sui dataset della tesi combina le misure.",
        "quando_funziona": ["Stampe e replay con perdita di nitidezza, rumore aggiunto o doppia compressione.", "Misure standard della letteratura sulla qualità d'immagine, calcolate in pochi millisecondi."],
        "limiti": ["Senza SVM addestrata non c'è verdetto.", "Dipende dalla camera: un'immagine reale di bassa qualità sembra un attacco, un replay in alta risoluzione sembra reale.", "BRISQUE non è incluso (richiede i file del modello di opencv_contrib)."],
        "esempi": [{"titolo": "Selfie nitido", "testo": "SSIM con la copia sfocata bassa (l'immagine perde molto quando la si sfoca), Laplaciano alto, pochi blocchi JPEG."}, {"titolo": "Replay su tablet", "testo": "SSIM alta (già morbida), indice JPEG peggiore, rumore del sensore doppio."}],
        "riferimenti": [{"testo": "Galbally, Marcel, Fierrez, Image Quality Assessment for Fake Biometric Detection, IEEE TIP 2014", "url": "https://doi.org/10.1109/TIP.2013.2292332"}, {"testo": "Wang, Sheikh, Bovik, No-reference perceptual quality assessment of JPEG compressed images, ICIP 2002", "url": "https://doi.org/10.1109/ICIP.2002.1038064"}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio quadrato con margine del 10 %.", "esempio": "—"},
            "gray": {"spiegazione": "Luminanza a 256×256.", "esempio": "—"},
            "reference": {"spiegazione": "Copia sfocata con gaussiana 3×3, σ = 0,5: il 'riferimento' di Galbally.", "esempio": "—"},
            "fullref": {"spiegazione": "MSE, PSNR, SNR, SC, MD, AD, NAE, RAMD, LMSE, NXC, SSIM, TED tra immagine e riferimento.", "esempio": "SSIM vicino a 1 = l'immagine era già sfocata."},
            "noref": {"spiegazione": "Indice JPEG (Wang 2002), HLFI, varianza del Laplaciano, sfocatura di Crété, rumore, entropia.", "esempio": "—"},
            "features": {"spiegazione": "Le 18 misure in un vettore.", "esempio": "—"},
            "clf": {"spiegazione": "SVM RBF addestrata con scripts/train_classic.py.", "esempio": "—"},
            "verdict": {"spiegazione": "P(reale) ≥ 0,5 → reale.", "esempio": "—"},
        },
    },
    "clip_probe": {
        "cosa_fa": "Linear probe su CLIP: lo stesso encoder immagine del CLIP zero-shot produce un vettore a 512 dimensioni; sopra c'è solo una regressione logistica addestrata sui dataset della tesi. Nessun peso dell'encoder viene toccato. Serve a rispondere a una domanda precisa: quanto sanno già le feature di CLIP sul liveness, prima di qualsiasi fine-tuning (FLIP)? Il benchmark di Fang et al. (2026) mostra che le sonde lineari vanno bene intra-dataset e poco cross-dataset.",
        "quando_funziona": ["Sullo stesso dataset del training: le feature di CLIP separano bene reale e attacco con pochi esempi.", "Confronto diretto con il CLIP zero-shot: stesso ritaglio, stesso encoder, cambia solo la testa."],
        "limiti": ["Senza classificatore addestrato non c'è verdetto.", "Cross-dataset cala: la sonda impara i tratti del dataset (camera, supporto), non il concetto generale.", "Encoder a 224×224: i dettagli finissimi della stampa vanno persi."],
        "esempi": [{"titolo": "Intra-dataset", "testo": "Addestrata e valutata su NUAA: accuracy alta con 3.000 immagini."}, {"titolo": "Cross-dataset", "testo": "La stessa sonda su CelebA-Spoof perde molto: lo stesso fenomeno delle CNN."}],
        "riferimenti": [{"testo": "Radford et al., Learning Transferable Visual Models From Natural Language Supervision (CLIP), ICML 2021", "url": "https://arxiv.org/abs/2103.00020"}, {"testo": "Fang et al., linear-probing benchmark di 24 encoder per il face PAD, IJCB 2026", "url": "https://arxiv.org/abs/2607.26993"}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio con margine del 35 %, come il CLIP zero-shot.", "esempio": "—"},
            "prep": {"spiegazione": "224×224 e normalizzazione di CLIP.", "esempio": "—"},
            "img_enc": {"spiegazione": "ViT-B/32 congelato: 512 valori.", "esempio": "—"},
            "embed": {"spiegazione": "Il vettore normalizzato è l'ingresso del classificatore, che lo standardizza con media e deviazione del training set.", "esempio": "—"},
            "clf": {"spiegazione": "Regressione logistica (scikit-learn) addestrata con scripts/train_classic.py.", "esempio": "—"},
            "verdict": {"spiegazione": "P(reale) ≥ 0,5 → reale.", "esempio": "—"},
        },
    },
    "dinov2_probe": {
        "cosa_fa": "Linear probe su DINOv2-small (Oquab et al. 2023): un Vision Transformer addestrato senza etichette e senza testo, per distillazione auto-supervisionata su 142 milioni di immagini. Il token [CLS] (384 valori) descrive l'immagine; una regressione logistica addestrata sui dataset della tesi decide reale/attacco. È il rappresentante dei foundation model 'solo visione', da confrontare con CLIP (visione + testo).",
        "quando_funziona": ["Intra-dataset: le feature DINOv2 catturano bene texture e struttura, spesso meglio di CLIP.", "Encoder piccolo (22 M parametri): millisecondi per immagine."],
        "limiti": ["Senza classificatore addestrato non c'è verdetto; i pesi vanno scaricati con scripts/download_models.py.", "Cross-dataset poco affidabile, come per tutte le sonde lineari.", "Patch da 14 pixel a 224×224: il moiré fine può sfuggire."],
        "esempi": [{"titolo": "Mappa dei token", "testo": "La norma dei token di patch si accende su occhi, bocca e bordi: dove il modello trova struttura."}, {"titolo": "Stampa", "testo": "Mappa più uniforme e piatta: la stampa ha meno struttura locale."}],
        "riferimenti": [{"testo": "Oquab et al., DINOv2: Learning Robust Visual Features without Supervision, TMLR 2024", "url": "https://arxiv.org/abs/2304.07193"}, {"testo": "Fang et al., linear-probing benchmark di 24 encoder per il face PAD, IJCB 2026", "url": "https://arxiv.org/abs/2607.26993"}],
        "passi": {
            "input": {"spiegazione": "Lettura dell'immagine.", "esempio": "—"}, "face": {"spiegazione": "Riquadro del volto.", "esempio": "—"},
            "crop": {"spiegazione": "Ritaglio con margine del 35 %.", "esempio": "—"},
            "prep": {"spiegazione": "224×224, normalizzazione ImageNet, 16×16 patch da 14 px.", "esempio": "—"},
            "img_enc": {"spiegazione": "ViT-S/14 congelato; la mappa mostra la norma dei token di patch.", "esempio": "—"},
            "embed": {"spiegazione": "Token [CLS] normalizzato: 384 valori.", "esempio": "—"},
            "clf": {"spiegazione": "Regressione logistica addestrata con scripts/train_classic.py.", "esempio": "—"},
            "verdict": {"spiegazione": "P(reale) ≥ 0,5 → reale.", "esempio": "—"},
        },
    },
}

