"""
Inventario per la scheda C1 (Markdown): CNN, dataset e checkpoint con provenienza, protocollo, hash SHA-256 e metriche
sul test dell'addestramento, più i modelli pre-addestrati scaricati (revisione fissata) e i classificatori dei metodi
classici. Sorgenti: models/weights/*.json, models/weights/PROVENANCE.md, data/eval/<ds>/info.json, results/c1/<ds>_config.json.
Uso:  python scripts/make_c1_inventory.py [--out results/c1/inventory.md]
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from tesi_app.paths import DATA, RESULTS, WEIGHTS  # noqa: E402

ARCH_LABEL = {"LivenessNet": "LivenessNet", "AttackNetV1": "AttackNet V1", "AttackNetV2_1": "AttackNet V2.1", "AttackNetV2_2": "AttackNet V2.2"}
DS_LABEL = {"nuaa": "NUAA Imposter", "casia_fasd": "CASIA-FASD", "celeba_spoof": "CelebA-Spoof", "synthaspoof": "SynthASpoof"}
# descrizioni in inglese per l'inventario consegnato al gruppo (i file info.json restano in italiano per l'app)
DS_EN = {
    "nuaa": ("NUAA Imposter (official test set)", "Tan, Li, Liu, Jiang, NUAA Photograph Imposter Database, ECCV 2010; public Hugging Face mirror `akahana/anti-spoofing-nuaaaa`",
             "academic use; unofficial mirror of a public dataset", "printed A4 photographs re-captured by webcam; 150 bona fide + 150 attacks taken at a constant step over the official test lists (3,362 bona fide, 5,761 attacks); bona fide from 9 subjects, attacks from 15"),
    "casia_fasd": ("CASIA-FASD (official test set, frames)", "Zhang et al., A face antispoofing database with diverse attacks, ICB 2012; public Hugging Face mirror `akahana/anti-spoofing-casiafasd`",
                   "academic use; unofficial mirror of a public dataset", "frames extracted from the test videos: printed photo, cut photo and video replay attacks, three camera qualities; 150 bona fide + 150 attack frames"),
    "celeba_spoof": ("CelebA-Spoof (subset)", "Zhang et al., CelebA-Spoof: Large-Scale Face Anti-Spoofing Dataset with Rich Annotations, ECCV 2020; public Hugging Face mirror `nguyenkhoa/celeba-spoof-for-face-antispoofing-test` (shard 0 of 10)",
                     "non-commercial research (CelebA-Spoof licence)", "pre-cropped faces; print, cut, replay (tablet/phone) and mask attacks in varied environments; 150 bona fide + 150 attacks"),
    "synthaspoof": ("SynthASpoof (synthetic)", "Fang, Huber, Damer, SynthASpoof: Developing Face Presentation Attack Detection Based on Privacy-friendly Synthetic Data, CVPR Workshops 2023; Google Drive archive linked in the authors' repository (github.com/meilfang/SynthASpoof)",
                    "CC BY-NC-SA 4.0, research only; public link, no registration", "synthetic bona fide (StyleGAN2-ADA, no real face) and attacks re-capturing them (print 3,800; webcam, iPad and Samsung replay 25,000 each); no official protocol: our split by synthetic identity, one in ten held out; 150 bona fide + 150 attacks (about 37 per attack type) from the held-out part"),
}
PRETRAINED = [
    ("MiniFASNet (Silent-Face-Anti-Spoofing)", "minifasnet", "github.com/minivision-ai/Silent-Face-Anti-Spoofing, Apache-2.0; two .pth files in resources/anti_spoof_models", "submodule commit in config"),
    ("CLIP ViT-B/32 (zero-shot and linear probe)", "clip_zeroshot, clip_probe", "Hugging Face openai/clip-vit-base-patch32", "revision pinned in scripts/download_models.py"),
    ("Depth Anything V2 small", "depth", "Hugging Face depth-anything/Depth-Anything-V2-Small-hf", "revision pinned in scripts/download_models.py"),
    ("DINOv2 small (linear probe)", "dinov2_probe", "Hugging Face facebook/dinov2-small", "revision pinned in scripts/download_models.py"),
    ("RetinaFace (face detection)", "all analyzers", "Silent-Face-Anti-Spoofing resources/detection_model (Caffe)", "submodule"),
    ("MediaPipe Face Mesh", "facemesh", "mediapipe 0.10.14 bundled model", "descriptive analyzer, no score"),
]


def pct(x):
    return "—" if x is None else f"{100 * x:.1f} %"


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--out", default=str(RESULTS / "c1" / "inventory.md"))
    a = ap.parse_args()
    cards = {}
    for c in sorted(WEIGHTS.glob("*.json")):
        if c.name == "manifest.json":
            continue
        cards[c.stem] = json.loads(c.read_text(encoding="utf-8"))
    L = ["# C1 inventory: CNNs, datasets and checkpoints", "",
         "Generated by `scripts/make_c1_inventory.py` from the checkpoint cards in `models/weights/*.json` (one JSON per weight file, written by the training scripts) and `data/eval/<dataset>/info.json`. Weight files are not in the repository; their SHA-256 is.", ""]
    # 1) datasets
    L += ["## Datasets", "", "| id | name | source | licence / access | evaluation subset |", "|---|---|---|---|---|"]
    for ds in ("nuaa", "casia_fasd", "celeba_spoof", "synthaspoof"):
        info_p = DATA / "eval" / ds / "info.json"
        info = json.loads(info_p.read_text(encoding="utf-8")) if info_p.exists() else {}
        n_real = len(list((DATA / "eval" / ds / "real").glob("*"))) if (DATA / "eval" / ds / "real").exists() else 0
        n_att = len(list((DATA / "eval" / ds / "attack").glob("*"))) if (DATA / "eval" / ds / "attack").exists() else 0
        name, source, licence, subset = DS_EN[ds]
        L.append(f"| `{ds}` | {name} | {source} | {licence} | {subset} |")
    L += ["", "MSSpoof and 3DMAD (Idiap) are not available yet: licence requests pending (handled by the coordinator); no Idiap material is part of this delivery.",
          "Role in C1: the CNN checkpoints are 24: 4 trained on NUAA with the official split (the reference rows of the table), 4 trained on NUAA with the pooled split (listed here, excluded from the table) and 16 trained on CASIA-FASD, CelebA-Spoof or SynthASpoof (12 with the official or identity split, 4 pooled), which appear in the same table only as cross-dataset rows (trained elsewhere, tested on NUAA); no C1 result depends on them.",
          "SynthASpoof: synthetic dataset (bona fide generated with StyleGAN2-ADA, no real face; attacks obtained by printing or replaying those faces). Licence CC BY-NC-SA 4.0, research use only; obtained on 2026-09-25 from the Google Drive archive linked in the authors' official repository (github.com/meilfang/SynthASpoof), which is publicly shared and required no registration or request form. The authors propose it as training data only and provide no evaluation protocol: the split used here (`scripts/prepare_datasets.py`) is our own deterministic split by synthetic identity, one identity in ten held out with all its attacks (the checkpoint cards call it `official` only in the sense of \"not pooled\"). The four SynthASpoof checkpoints were trained by the operator on 2026-09-25 with the same script and settings as the others (1,500 images per class, validation by identity); they are the only artefacts derived from SynthASpoof.", ""]
    # 2) CNN checkpoints
    L += ["## CNN checkpoints (trained with `scripts/train_cnn.py`)", "",
          "Protocol *official*: official train/test split of the dataset, validation by subject inside the training set. Protocol *pooled*: all images pooled and split 80/20 at random, as in the reference code (subjects and sessions shared between train and test; these variants are never evaluated on their own dataset). Test metrics are those computed at training time on the checkpoint's own test split, threshold 0.5.", "",
          "The `file` column is the file the application loads (`.h5`, classic HDF5 weights) and `SHA-256` is its hash, the one written in the card and used as the analyzer fingerprint. Every checkpoint also exists as a `.keras` copy saved by the same training run (its hash is listed in `config/nuaa_config.json`, `other_formats`); it is not used by the evaluation. Before a new inference the file hash is checked against the card (`scripts/eval_dataset.py`).", "",
          "| architecture | training dataset | protocol | file | SHA-256 | train / val / test | epochs | test ACER | test EER | test AUC | saved |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for stem, d in sorted(cards.items(), key=lambda kv: (kv[1].get("dataset", ""), kv[1].get("protocol", ""), kv[0])):
        if "arch" not in d:
            continue
        wf = next((stem + ext for ext in (".h5", ".weights.h5", ".keras") if (WEIGHTS / (stem + ext)).exists()), stem)   # il file caricato dall'app
        t = d.get("test", {})
        L.append(f"| {ARCH_LABEL.get(d['arch'], d['arch'])} | {DS_LABEL.get(d['dataset'], d['dataset'])} | {d.get('protocol', '')} | `{wf}` | `{d.get('weights_sha256', '')}` | "
                 f"{d.get('n_train', '')} / {d.get('n_val', '')} / {d.get('n_test', '')} | {d.get('epochs_run', '')} | {pct(t.get('acer'))} | {pct(t.get('eer'))} | {'—' if t.get('auc') is None else format(t['auc'], '.3f')} | {d.get('saved', '')} |")
    prov = WEIGHTS / "PROVENANCE.md"
    if prov.exists():
        L += ["", "Provenance notes for the checkpoints (training before the script entered the repository, formats, reconciliation of the copies) are in `checkpoints/PROVENANCE.md` (English version of the note kept with the weights).", ""]
    # 3) classic classifiers
    L += ["## Classifiers of the classic methods and linear probes (trained with `scripts/train_classic.py`)", "",
          "| analyzer | classifier | training dataset | protocol | feature dim | file | SHA-256 | test ACER | test EER |", "|---|---|---|---|---|---|---|---|---|"]
    for stem, d in sorted(cards.items()):
        if "analyzer" not in d:
            continue
        t = d.get("test", {})
        L.append(f"| `{d['analyzer']}` | {d.get('classifier', '')} | {DS_LABEL.get(d.get('dataset', ''), d.get('dataset', ''))} | {d.get('protocol', '')} | {d.get('feature_dim', '')} | `{stem}.joblib` | `{d.get('clf_sha256', '')}` | {pct(t.get('acer'))} | {pct(t.get('eer'))} |")
    # 4) pretrained
    L += ["", "## Pre-trained models (downloaded, not trained here)", "", "| model | analyzer(s) | origin | version pinning |", "|---|---|---|---|"]
    for name, aid, origin, pin in PRETRAINED:
        L.append(f"| {name} | `{aid}` | {origin} | {pin} |")
    L += ["", "Exact revisions and file hashes of the pre-trained models are recorded per analyzer as the `fingerprint` field in `config/nuaa_config.json` (the same fingerprint is stored with every cached score and invalidates it when the model changes). External pretraining: the 24 CNN checkpoints are trained from scratch (random initialisation) on the dataset named in their card, with no external weights or data. Of the six classifiers, four (LBP, DoG, IDA, IQA) are trained on hand-crafted features of NUAA and use no pre-trained model; the two linear probes are logistic regressions trained on NUAA over frozen embeddings of pre-trained backbones (CLIP ViT-B/32, DINOv2 small), so their backbone carries external pretraining while the classifier itself is trained here. The pre-trained models above are third-party artefacts used as-is (MiniFASNet as a scorer, CLIP zero-shot, Depth Anything as an estimator, RetinaFace as a detector), trained by their authors on data not controlled by this project (MiniFASNet on proprietary data, per its authors).", ""]
    Path(a.out).write_text("\n".join(L), encoding="utf-8")
    print("inventario:", a.out, f"({sum(1 for d in cards.values() if 'arch' in d)} CNN, {sum(1 for d in cards.values() if 'analyzer' in d)} classificatori)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
