"""
Inventario per la scheda C1 (Markdown): CNN, dataset e checkpoint con provenienza, protocollo, hash SHA-256 e metriche
sul test dell'addestramento, più i modelli pre-addestrati scaricati (revisione fissata) e i classificatori dei metodi
classici. Sorgenti: models/weights/*.json, models/weights/PROVENANCE.md, data/eval/<ds>/info.json, results/c1/<ds>_config.json.
Uso:  python scripts/make_c1_inventory.py [--out results/c1/inventory.md]
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from tesi_app.paths import DATA, WEIGHTS  # noqa: E402

ARCH_LABEL = {"LivenessNet": "LivenessNet", "AttackNetV1": "AttackNet V1", "AttackNetV2_1": "AttackNet V2.1", "AttackNetV2_2": "AttackNet V2.2"}
DS_LABEL = {"nuaa": "NUAA Imposter", "casia_fasd": "CASIA-FASD", "celeba_spoof": "CelebA-Spoof", "synthaspoof": "SynthASpoof"}
PRETRAINED = [
    ("MiniFASNet (Silent-Face-Anti-Spoofing)", "minifasnet", "github.com/minivision-ai/Silent-Face-Anti-Spoofing, Apache-2.0; two .pth files in resources/anti_spoof_models", "submodule commit in config"),
    ("CLIP ViT-B/32 (zero-shot and linear probe)", "clip_zeroshot, clip_probe", "Hugging Face openai/clip-vit-base-patch32", "revision pinned in scripts/download_models.py"),
    ("Depth Anything V2 small", "depth", "Hugging Face depth-anything/Depth-Anything-V2-Small-hf", "revision pinned in scripts/download_models.py"),
    ("DINOv2 small (linear probe)", "dinov2_probe", "Hugging Face facebook/dinov2-small", "revision pinned in scripts/download_models.py"),
    ("RetinaFace (face detection)", "all analyzers", "Silent-Face-Anti-Spoofing resources/detection_model (Caffe)", "submodule"),
    ("MediaPipe Face Mesh", "facemesh", "mediapipe 0.10.14 bundled model", "descriptive analyzer, no score"),
]


def pct(x):
    return "—" if x is None else f"{100 * x:.1f} %"


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--out", default=str(ROOT / "results" / "c1" / "inventory.md"))
    a = ap.parse_args()
    cards = {}
    for c in sorted(WEIGHTS.glob("*.json")):
        if c.name == "manifest.json":
            continue
        cards[c.stem] = json.loads(c.read_text(encoding="utf-8"))
    L = ["# C1 inventory: CNNs, datasets and checkpoints", "",
         "Generated by `scripts/make_c1_inventory.py` from the checkpoint cards in `models/weights/*.json` (one JSON per weight file, written by the training scripts) and `data/eval/<dataset>/info.json`. Weight files are not in the repository; their SHA-256 is.", ""]
    # 1) datasets
    L += ["## Datasets", "", "| id | name | source | licence / access | evaluation subset |", "|---|---|---|---|---|"]
    for ds in ("nuaa", "casia_fasd", "celeba_spoof", "synthaspoof"):
        info_p = DATA / "eval" / ds / "info.json"
        info = json.loads(info_p.read_text(encoding="utf-8")) if info_p.exists() else {}
        n_real = len(list((DATA / "eval" / ds / "real").glob("*"))) if (DATA / "eval" / ds / "real").exists() else 0
        n_att = len(list((DATA / "eval" / ds / "attack").glob("*"))) if (DATA / "eval" / ds / "attack").exists() else 0
        L.append(f"| `{ds}` | {info.get('name', DS_LABEL[ds])} | {info.get('source', '')} | {info.get('license', '')} | {n_real} bona fide + {n_att} attacks: {info.get('note', '')} |")
    L += ["", "MSSpoof and 3DMAD (Idiap) are not yet available: licence pending.", ""]
    # 2) CNN checkpoints
    L += ["## CNN checkpoints (trained with `scripts/train_cnn.py`)", "",
          "Protocol *official*: official train/test split of the dataset, validation by subject inside the training set. Protocol *pooled*: all images pooled and split 80/20 at random, as in the reference code (subjects and sessions shared between train and test; these variants are never evaluated on their own dataset). Test metrics are those computed at training time on the checkpoint's own test split, threshold 0.5.", "",
          "| architecture | training dataset | protocol | file | SHA-256 | train / val / test | epochs | test ACER | test EER | test AUC | saved |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for stem, d in sorted(cards.items(), key=lambda kv: (kv[1].get("dataset", ""), kv[1].get("protocol", ""), kv[0])):
        if "arch" not in d:
            continue
        wf = next((stem + ext for ext in (".keras", ".h5") if (WEIGHTS / (stem + ext)).exists()), stem)
        t = d.get("test", {})
        L.append(f"| {ARCH_LABEL.get(d['arch'], d['arch'])} | {DS_LABEL.get(d['dataset'], d['dataset'])} | {d.get('protocol', '')} | `{wf}` | `{d.get('weights_sha256', '')}` | "
                 f"{d.get('n_train', '')} / {d.get('n_val', '')} / {d.get('n_test', '')} | {d.get('epochs_run', '')} | {pct(t.get('acer'))} | {pct(t.get('eer'))} | {'—' if t.get('auc') is None else format(t['auc'], '.3f')} | {d.get('saved', '')} |")
    prov = WEIGHTS / "PROVENANCE.md"
    if prov.exists():
        L += ["", "Provenance notes for the checkpoints trained on 2026-09-12 (before the training script entered the repository) are in `models/weights/PROVENANCE.md`, reproduced in the delivery folder.", ""]
    # 3) classic classifiers
    L += ["## Classifiers of the classic methods and linear probes (trained with `scripts/train_classic.py`)", "",
          "| analyzer | classifier | training dataset | protocol | feature dim | file | SHA-256 | test ACER | test EER |", "|---|---|---|---|---|---|---|---|---|"]
    for stem, d in sorted(cards.items()):
        if "analyzer" not in d:
            continue
        t = d.get("test", {})
        L.append(f"| `{d['analyzer']}` | {d.get('classifier', '')} | {DS_LABEL.get(d.get('dataset', ''), d.get('dataset', ''))} | {d.get('protocol', '')} | {d.get('feature_dim', '')} | `{stem}.joblib` | `{d.get('clf_sha256', '')}` | {pct(t.get('acer'))} | {pct(t.get('eer'))} |")
    # 4) pretrained
    L += ["", "## Pre-trained models (downloaded, not trained here)", "", "| model | analyzer(s) | origin | version pinning |", "|---|---|---|---|"]
    for name, aid, origin, pin in PRETRAINED:
        L.append(f"| {name} | `{aid}` | {origin} | {pin} |")
    L += ["", "Exact revisions and file hashes of the pre-trained models are recorded per analyzer as the `fingerprint` field in `config/nuaa_config.json` (the same fingerprint is stored with every cached score and invalidates it when the model changes).", ""]
    Path(a.out).write_text("\n".join(L), encoding="utf-8")
    print("inventario:", a.out, f"({sum(1 for d in cards.values() if 'arch' in d)} CNN, {sum(1 for d in cards.values() if 'analyzer' in d)} classificatori)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
